services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "${DB_PORT:-5435}:5432"
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - todolist-network

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todolist
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - todolist-network

volumes:
  postgres_data:

networks:
  bank-rest-network:
    driver: bridge

