spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/todolist_test
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true

  flyway:
    enabled: false
    baseline-on-migrate: false
    fail-on-missing-locations: false

  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.test.context: DEBUG
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG